### ISSUE TITLE
Error appeared when running the examples

### ISSUE THREAD

**Issue by Muqi-Zou** [grimm-co/GEARSHIFT#8]
I generated the simple by using make, and trying to run go.py on the following decompiled code: 
```
undefined4 FUN_001011a1(undefined4 *param_1)

{
  void *pvVar1;
  
  pvVar1 = malloc(8);
  *(void **)(param_1 + 6) = pvVar1;
  FUN_0010117a(param_1 + 4);
  FUN_0010117a(*(int **)(param_1 + 6));
  *param_1 = 2;
  *(undefined *)(param_1 + 1) = 7;
  *(undefined8 *)(param_1 + 2) = 8;
  return *param_1;
}
```
And I received following errors:
```
go.py> Running...
Forwards analysis FUN_001011a1
array(ghidra.program.model.listing.Parameter, [[undefined4 * param_1@RDI:8]])
type of func_proto ghidra.program.model.pcode.FunctionPrototype@cdda9ba
type of func_proto.getParam(i) ghidra.program.model.pcode.HighSymbol@8d3ca18
Traceback (most recent call last):
  File "/home/muqi/ghidra_scripts/go.py", line 68, in <module>
    argument_varnodes = PCodeInterpreter.analyzeFunctionForward(currentFunction, pci)
  File "/home/muqi/ghidra_scripts/PCodeInterpreter.py", line 669, in analyzeFunctionForward
    argument_varnodes.append(func_proto.getParam(i).getRepresentative())
AttributeError: 'ghidra.program.model.pcode.HighSymbol' object has no attribute 'getRepresentative'
go.py> Finished!
```
My gcc version is (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
My ghidra version is: Version 9.2 , which downloaded from github on Nov-02,2020
My Java Version is: 11.0.8

Could I have some hints about how to fix this?

Thanks!

**Comment by Muqi-Zou** [comment]
It looks like there are some differences between the [codes](https://github.com/NationalSecurityAgency/ghidra/blob/bda4e1dc19bec94efa11e016894a0e20436983a7/Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/pcode/FunctionPrototype.java#L216) and [docs](https://ghidra.re/ghidra_docs/api/ghidra/program/model/pcode/FunctionPrototype.html#getParam(int)) given by ghidra.
I used the [getParam](https://ghidra.re/ghidra_docs/api/ghidra/program/model/pcode/LocalSymbolMap.html#getParam(int)) in [LocalSymbolMap](https://ghidra.re/ghidra_docs/api/ghidra/program/model/pcode/HighFunction.html#getLocalSymbolMap()) instead and it solves this problem.

**Comment by saruman9** [comment]
It's old docs (and are not updated), I think for Ghidra 9.1. I think also, that the GEARSHIFT was developed for the last stable version (not for upstream version).

**Comment by AreTillery** [comment]
Thanks for the ticket! It sounds like there's a workaround, and I'll look into a fix in the next couple of months if no one has submitted a pull request by the time I finish with my current training engagement.

Yes, we developed for Ghidra 9.1. GEARSHIFT was written in July-August and then our release was delayed a bit by some internal client work that took away our time to do a final review; there may need to be some changes made for the newest version of Ghidra.
