### ISSUE TITLE
Improve speed with winafl

### ISSUE THREAD

**Issue by jplopezy** [grimm-co/GEARSHIFT#9]
This tool is very useful when doing a harness but what I notice that the speed of the tests in winafl is very slow.

Obviously the harness could be optimized, but I wanted to know if they already did tests of this style or for example implement charToWChar

a greeting

**Comment by AreTillery** [comment]
Hi, @jplopezy,

The tool is designed to create somewhat generic harnesses, so it won't be optimized for a particular fuzzer. We'd be happy to take pull requests that improve this in some way (for example, allowing a particular target fuzzer as an argument).

As for particular tests on the speed of the created harness in different fuzzers, we did not - this tool is intended to make the harness creation easier by automating the analysis of structures, but there will always be further modification or customization that could improve the performance afterwords through manual steps.
